type = "javascript"

name = "<YOUR WORKER NAME>"
account_id = "<YOUR ACCOUNT ID>"
zone_id = "<YOUR ZONE ID>"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"
dir = "build"
